# Generated by Django 3.2.22 on 2024-10-29 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('idemp', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=255)),
                ('contact', models.IntegerField()),
                ('city', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'emp',
                'managed': False,
            },
        ),
    ]
